from __future__ import annotations

from typing import Any, Dict, Optional

from self_correcting_langgraph_agent.runtime import RUNTIME_TRACE_TYPE
from self_correcting_langgraph_agent.service.errors import ERROR_CODES, READINESS_FAILED

ALLOWED_HTTP_METHODS = "GET, HEAD, OPTIONS, POST"
COMMON_RESPONSE_HEADERS = {
    "X-Request-ID": {
        "description": "Request correlation identifier echoed or generated by the service",
        "schema": {"type": "string"},
    },
    "X-Content-Type-Options": {
        "description": "Content sniffing protection",
        "schema": {"type": "string", "const": "nosniff"},
    },
    "Cache-Control": {
        "description": "Disable client and intermediary response caching",
        "schema": {"type": "string", "const": "no-store"},
    },
    "Referrer-Policy": {
        "description": "Prevent referrer leakage from browser or proxy contexts",
        "schema": {"type": "string", "const": "no-referrer"},
    },
    "Content-Security-Policy": {
        "description": "Disable browser-executed content and framing for API responses",
        "schema": {
            "type": "string",
            "const": "default-src 'none'; frame-ancestors 'none'; base-uri 'none'",
        },
    },
    "X-Frame-Options": {
        "description": "Deny legacy browser framing of API responses",
        "schema": {"type": "string", "const": "DENY"},
    },
}


def service_openapi() -> Dict[str, Any]:
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "Self-Correcting LangGraph Agent API",
            "version": "0.1.0",
        },
        "components": {
            "securitySchemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                }
            },
            "schemas": {
                "HealthResponse": {
                    "type": "object",
                    "required": ["status"],
                    "properties": {
                        "status": {"type": "string", "const": "ok"},
                    },
                },
                "ReadinessResponse": {
                    "type": "object",
                    "required": ["status", "checks", "failed_checks"],
                    "properties": {
                        "status": {"type": "string", "enum": ["ready", "not_ready"]},
                        "checks": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "error_code": {"type": "string", "const": READINESS_FAILED},
                        "failed_checks": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                },
                "ConfigResponse": {
                    "type": "object",
                    "properties": _diagnostic_audit_properties(),
                    "additionalProperties": {"type": "string"},
                },
                "VersionResponse": {
                    "type": "object",
                    "required": ["version"],
                    "properties": {
                        "version": {"type": "string"},
                    },
                },
                "ToolsResponse": {
                    "type": "object",
                    "required": ["tools"],
                    "properties": {
                        "tools": {
                            "type": "array",
                            "items": {"type": "object"},
                        },
                    },
                },
                "RuntimeToolsResponse": {
                    "type": "object",
                    "required": ["tools"],
                    "properties": {
                        "tools": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/RuntimeToolMetadata"},
                        },
                    },
                },
                "RuntimeToolMetadata": {
                    "type": "object",
                    "required": [
                        "name",
                        "description",
                        "approval_required_by_default",
                        "input_schema",
                        "output_schema",
                        "timeout_seconds",
                    ],
                    "properties": {
                        "name": {"type": "string"},
                        "description": {"type": "string"},
                        "approval_required_by_default": {
                            "type": "string",
                            "enum": ["true", "false"],
                        },
                        "input_schema": {"type": "object"},
                        "output_schema": {"type": "object"},
                        "timeout_seconds": {
                            "type": "string",
                            "pattern": r"^\d+\.\d$",
                        },
                    },
                    "additionalProperties": False,
                },
                "MetricsResponse": {
                    "type": "object",
                    "properties": _diagnostic_audit_properties(),
                    "additionalProperties": {
                        "oneOf": [
                            {"type": "string"},
                            {
                                "type": "object",
                                "additionalProperties": {"type": "string"},
                            },
                        ]
                    },
                },
                "RunRequest": {
                    "type": "object",
                    "required": ["goal"],
                    "properties": {
                        "goal": {"type": "string", "maxLength": 4096},
                        "max_steps": {"type": "integer", "minimum": 1},
                        "max_retries": {"type": "integer", "minimum": 0},
                        "full_trace": {
                            "type": "boolean",
                            "description": (
                                "Request a full internal trace response; disabled by default "
                                "unless the service is explicitly configured to allow it."
                            ),
                        },
                    },
                },
                "RunResponse": {
                    "type": "object",
                    "required": ["status"],
                    "properties": {
                        "status": {
                            "type": "string",
                            "enum": ["done", "failed"],
                        },
                        "answer": {"type": "string"},
                        "error": {"type": "string"},
                        "summary": {"type": "string"},
                        "trace_path": {"type": "string"},
                        "steps": {"type": "array", "items": {"type": "object"}},
                    },
                    "additionalProperties": True,
                },
                "RuntimeRunRequest": {
                    "type": "object",
                    "required": ["goal"],
                    "properties": {
                        "goal": {"type": "string", "maxLength": 4096},
                        "plan": {
                            "type": "object",
                            "description": (
                                "Optional strict runtime plan for deterministic tests; "
                                "when omitted the service uses configured LLM provider env."
                            ),
                        },
                        "plan_sequence": {
                            "type": "array",
                            "minItems": 1,
                            "items": {"type": "object"},
                            "description": (
                                "Optional ordered strict runtime plans for deterministic "
                                "replay tests; mutually exclusive with plan."
                            ),
                        },
                        "max_iterations": {
                            "type": "integer",
                            "minimum": 1,
                            "description": (
                                "Bounded by the service runtime_max_iterations configuration."
                            ),
                        },
                        "approved_action_ids": {
                            "type": "array",
                            "uniqueItems": True,
                            "items": {"type": "string", "minLength": 1},
                        },
                        "metadata": {
                            "type": "object",
                            "maxProperties": 16,
                            "additionalProperties": {
                                "type": "string",
                                "maxLength": 256,
                            },
                            "description": (
                                "Optional non-secret string metadata for internal "
                                "audit and filtering."
                            ),
                        },
                        "tags": {
                            "type": "array",
                            "maxItems": 16,
                            "uniqueItems": True,
                            "items": {
                                "type": "string",
                                "minLength": 1,
                                "maxLength": 64,
                            },
                            "description": (
                                "Optional non-secret run tags for internal audit "
                                "and filtering."
                            ),
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimeResumeRequest": {
                    "type": "object",
                    "required": ["run_id", "approved_action_ids"],
                    "properties": {
                        "run_id": {"type": "string"},
                        "approved_action_ids": {
                            "type": "array",
                            "uniqueItems": True,
                            "items": {"type": "string", "minLength": 1},
                        },
                        "max_iterations": {"type": "integer", "minimum": 1},
                    },
                    "additionalProperties": False,
                },
                "RuntimeCancelRequest": {
                    "type": "object",
                    "properties": {
                        "reason": {
                            "type": "string",
                            "maxLength": 500,
                            "description": (
                                "Optional operator-visible cancellation reason."
                            ),
                        }
                    },
                    "additionalProperties": False,
                },
                "RuntimeRunResponse": {
                    "type": "object",
                    "required": ["trace_type", "status", "plan", "observations", "events"],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "status": {
                            "type": "string",
                            "enum": [
                                "cancelled",
                                "done",
                                "failed",
                                "requires_approval",
                            ],
                        },
                        "run_id": {"type": "string"},
                        "goal": {"type": "string"},
                        "auth_subject": {"type": "string"},
                        "resumed_by_auth_subject": {"type": "string"},
                        "answer": {"type": "string"},
                        "final_answer_guardrail": _final_answer_guardrail_schema(),
                        "trace_path": {"type": "string"},
                        "duration_seconds": {
                            "type": "string",
                            "pattern": r"^\d+\.\d{4}$",
                        },
                        "iteration_count": {"type": "string"},
                        "max_iterations": {"type": "string"},
                        "iteration_budget_remaining": {"type": "string"},
                        "prompt_observation_compaction": {"type": "object"},
                        "approved_action_count": {"type": "string"},
                        "approved_action_ids": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                        "metadata": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "tags": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                        "plan": {"type": "object"},
                        "plans": {"type": "array", "items": {"type": "object"}},
                        "observations": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/RuntimeObservation"},
                        },
                        "events": {
                            "type": "array",
                            "items": {"$ref": "#/components/schemas/RuntimeEvent"},
                        },
                        "error_code": {"type": "string"},
                        "error": {"type": "string"},
                    },
                    "additionalProperties": True,
                },
                "RuntimeObservation": {
                    "type": "object",
                    "required": ["action_id", "tool", "status", "output"],
                    "properties": {
                        "action_id": {"type": "string"},
                        "tool": {"type": "string"},
                        "status": {
                            "type": "string",
                            "enum": ["ok", "failed", "requires_approval"],
                        },
                        "output": {"type": "object"},
                        "error_code": {"type": "string"},
                        "error": {"type": "string"},
                        "started_at": {"type": "string"},
                        "completed_at": {"type": "string"},
                        "duration_seconds": {
                            "type": "string",
                            "pattern": r"^\d+\.\d{4}$",
                        },
                    },
                    "additionalProperties": True,
                },
                "RuntimeEvent": {
                    "type": "object",
                    "required": ["node", "status"],
                    "properties": {
                        "node": {"type": "string"},
                        "status": {"type": "string"},
                        "iteration": {"type": "string"},
                        "action_id": {"type": "string"},
                        "tool": {"type": "string"},
                        "reason": {"type": "string"},
                        "action_count": {"type": "string"},
                        "started_at": {"type": "string"},
                        "completed_at": {"type": "string"},
                        "duration_seconds": {
                            "type": "string",
                            "pattern": r"^\d+\.\d{4}$",
                        },
                    },
                    "additionalProperties": True,
                },
                "RuntimeArtifactResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "run_id",
                        "trace_path",
                        "action_id",
                        "tool",
                        "artifact",
                    ],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "run_id": {"type": "string"},
                        "trace_path": {"type": "string"},
                        "action_id": {"type": "string"},
                        "tool": {"type": "string"},
                        "artifact": {"type": "object"},
                    },
                    "additionalProperties": False,
                },
                "RuntimeArtifactListResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "run_id",
                        "trace_path",
                        "count",
                        "artifacts",
                    ],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "run_id": {"type": "string"},
                        "trace_path": {"type": "string"},
                        "count": {"type": "string"},
                        "artifacts": {
                            "type": "array",
                            "items": {"type": "object"},
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimeTimelineResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "run_id",
                        "trace_path",
                        "event_count",
                        "progress_event_count",
                        "observation_count",
                        "events",
                        "progress_events",
                        "observations",
                    ],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "run_id": {"type": "string"},
                        "trace_path": {"type": "string"},
                        "event_count": {"type": "string"},
                        "progress_event_count": {"type": "string"},
                        "observation_count": {"type": "string"},
                        "events": {
                            "type": "array",
                            "items": {"type": "object"},
                        },
                        "progress_events": {
                            "type": "array",
                            "items": {"type": "object"},
                        },
                        "observations": {
                            "type": "array",
                            "items": {"type": "object"},
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimeRunStatusResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "run_id",
                        "status",
                        "trace_path",
                        "plan_count",
                        "observation_count",
                        "event_count",
                        "progress_event_count",
                    ],
                    "properties": _runtime_run_status_properties(
                        include_pending_approval=True
                    ),
                    "additionalProperties": False,
                },
                "RuntimeRunListItemResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "run_id",
                        "status",
                        "trace_path",
                        "plan_count",
                        "observation_count",
                        "event_count",
                        "progress_event_count",
                    ],
                    "properties": _runtime_run_status_properties(
                        include_pending_approval=False
                    ),
                    "additionalProperties": False,
                },
                "RuntimeRunListResponse": {
                    "type": "object",
                    "required": ["runs", "count", "next_cursor", "has_more"],
                    "properties": {
                        "runs": {
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/RuntimeRunListItemResponse"
                            },
                        },
                        "count": {"type": "string"},
                        "next_cursor": {"type": "string"},
                        "has_more": {
                            "type": "string",
                            "enum": ["true", "false"],
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimeRunSummaryResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "run_count",
                        "status_counts",
                        "auth_subject_counts",
                        "tool_counts",
                        "error_code_counts",
                        "failed_observation_count",
                        "approval_required_count",
                        "pending_approval_count",
                        "final_answer_guardrail_applied_count",
                        "final_answer_guardrail_reason_counts",
                        "artifact_count",
                        "artifact_total_bytes",
                        "tag_counts",
                        "metadata_key_counts",
                    ],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "run_count": {"type": "string"},
                        "status_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "auth_subject_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "tool_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "error_code_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "failed_observation_count": {"type": "string"},
                        "approval_required_count": {"type": "string"},
                        "pending_approval_count": {"type": "string"},
                        "final_answer_guardrail_applied_count": {"type": "string"},
                        "final_answer_guardrail_reason_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "artifact_count": {"type": "string"},
                        "artifact_total_bytes": {"type": "string"},
                        "tag_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "metadata_key_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimeApprovalQueueResponse": {
                    "type": "object",
                    "required": ["trace_type", "count", "approvals"],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "count": {"type": "string"},
                        "approvals": {
                            "type": "array",
                            "items": {"type": "object"},
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimeApprovalSummaryResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "pending_approval_count",
                        "stale_pending_count",
                        "max_pending_age_seconds",
                        "auth_subject_counts",
                        "tool_counts",
                    ],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "pending_approval_count": {"type": "string"},
                        "stale_pending_count": {"type": "string"},
                        "max_pending_age_seconds": {"type": "string"},
                        "auth_subject_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                        "tool_counts": {
                            "type": "object",
                            "additionalProperties": {"type": "string"},
                        },
                    },
                    "additionalProperties": False,
                },
                "RuntimePolicyResponse": {
                    "type": "object",
                    "required": [
                        "trace_type",
                        "auth_subject",
                        "is_admin",
                        "default_allowed_tools",
                        "global_allowed_tools",
                        "subject_policy_count",
                        "subject_allowed_tools",
                        "effective_allowed_tools",
                        "effective_policy_source",
                        "effective_tool_policy",
                        "effective_tool_policy_sha256",
                    ],
                    "properties": {
                        "trace_type": {
                            "type": "string",
                            "const": RUNTIME_TRACE_TYPE,
                        },
                        "auth_subject": {"type": "string"},
                        "is_admin": {"type": "string", "enum": ["true", "false"]},
                        "default_allowed_tools": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                        "global_allowed_tools": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                        "subject_policy_count": {"type": "string"},
                        "subject_allowed_tools": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                        },
                        "effective_allowed_tools": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                        "effective_policy_source": {
                            "type": "string",
                            "enum": ["default", "global", "subject"],
                        },
                        "effective_tool_policy": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": [
                                    "name",
                                    "allowed",
                                    "approval_required",
                                ],
                                "properties": {
                                    "name": {"type": "string"},
                                    "allowed": {
                                        "type": "string",
                                        "enum": ["true", "false"],
                                    },
                                    "approval_required": {
                                        "type": "string",
                                        "enum": ["true", "false"],
                                    },
                                },
                                "additionalProperties": False,
                            },
                        },
                        "effective_tool_policy_sha256": {
                            "type": "string",
                            "pattern": r"^[a-f0-9]{64}$",
                        },
                    },
                    "additionalProperties": False,
                },
                "ErrorResponse": {
                    "type": "object",
                    "required": ["status", "error_code", "error"],
                    "properties": {
                        "status": {"type": "string", "const": "failed"},
                        "error_code": {"type": "string", "enum": list(ERROR_CODES)},
                        "error": {"type": "string"},
                        "retry_after_seconds": {
                            "type": "string",
                            "pattern": r"^[1-9]\d*$",
                        },
                    },
                }
            },
        },
        "paths": {
            "/health": {
                "get": {
                    "summary": "Report service liveness",
                    "operationId": "getHealth",
                    "responses": {"200": _json_response("Service is live", "HealthResponse")},
                },
                "head": {
                    "summary": "Report service liveness headers",
                    "operationId": "headHealth",
                    "responses": {"200": _empty_response("Service is live")},
                },
            },
            "/ready": {
                "get": {
                    "summary": "Report service readiness",
                    "operationId": "getReady",
                    "responses": {
                        "200": _json_response("Service is ready", "ReadinessResponse"),
                        "503": _json_response("Service is not ready", "ReadinessResponse"),
                    },
                },
                "head": {
                    "summary": "Report service readiness headers",
                    "operationId": "headReady",
                    "responses": {
                        "200": _empty_response("Service is ready"),
                        "503": _empty_response("Service is not ready"),
                    },
                },
            },
            "/config": {
                "get": {
                    "summary": "Report redacted runtime configuration",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getConfig",
                    "responses": {
                        "200": _json_response("Redacted runtime config", "ConfigResponse")
                    },
                }
            },
            "/version": {
                "get": {
                    "summary": "Report package version",
                    "operationId": "getVersion",
                    "responses": {"200": _json_response("Package version", "VersionResponse")},
                }
            },
            "/tools": {
                "get": {
                    "summary": "List deterministic tool metadata",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getTools",
                    "responses": {"200": _json_response("Tool metadata", "ToolsResponse")},
                }
            },
            "/runtime/tools": {
                "get": {
                    "summary": "List Codex-style runtime tool metadata",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getRuntimeTools",
                    "responses": {
                        "200": _json_response(
                            "Runtime tool metadata",
                            "RuntimeToolsResponse",
                        )
                    },
                }
            },
            "/runtime/policy": {
                "get": {
                    "summary": "Report Codex-style runtime tool policy",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getRuntimePolicy",
                    "responses": {
                        "200": _json_response(
                            "Runtime tool execution policy",
                            "RuntimePolicyResponse",
                        ),
                        "401": _error_response("Missing or invalid bearer token"),
                    },
                }
            },
            "/metrics": {
                "get": {
                    "summary": "Report runtime request counters",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getMetrics",
                    "responses": {"200": _json_response("Runtime metrics", "MetricsResponse")},
                }
            },
            "/metrics.prom": {
                "get": {
                    "summary": "Report Prometheus text metrics",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getPrometheusMetrics",
                    "responses": {"200": _text_response("Prometheus text metrics")},
                }
            },
            "/openapi.json": {
                "get": {
                    "summary": "Report this API contract",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getOpenApi",
                    "responses": {"200": _object_response("OpenAPI contract")},
                }
            },
            "/run": {
                "options": {
                    "summary": "Report supported HTTP methods",
                    "operationId": "optionsRun",
                    "responses": {
                        "204": {
                            "description": f"Allow: {ALLOWED_HTTP_METHODS}",
                            "headers": _response_headers(
                                {
                                    "Allow": {
                                        "description": "Supported HTTP methods",
                                        "schema": {
                                            "type": "string",
                                            "const": ALLOWED_HTTP_METHODS,
                                        },
                                    }
                                }
                            ),
                        }
                    },
                },
                "post": {
                    "summary": "Run one bounded agent goal",
                    "operationId": "postRun",
                    "security": [{"BearerAuth": []}],
                    "parameters": [_idempotency_key_parameter()],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {"$ref": "#/components/schemas/RunRequest"}
                            }
                        },
                    },
                    "responses": {
                        "200": _json_response(
                            "Agent run completed or failed structurally",
                            "RunResponse",
                            headers={
                                "X-Run-ID": {
                                    "description": (
                                        "Agent run identifier for request/log/trace correlation"
                                    ),
                                    "schema": {"type": "string"},
                                },
                                "X-Trace-Path": {
                                    "description": (
                                        "Persisted trace artifact path when trace persistence "
                                        "is enabled"
                                    ),
                                    "schema": {"type": "string"},
                                }
                            },
                        ),
                        "400": _error_response(
                            "Malformed JSON, incomplete body, unsupported transfer encoding, "
                            "missing goal, or invalid config"
                        ),
                        "401": _error_response(
                            "Missing or invalid bearer token",
                            headers={
                                "WWW-Authenticate": {
                                    "description": "Bearer authentication challenge",
                                    "schema": {"type": "string", "const": "Bearer"},
                                }
                            },
                        ),
                        "403": _error_response("Full trace responses are disabled"),
                        "408": _error_response(
                            "Request body read timed out",
                            headers={
                                "Retry-After": {
                                    "description": "Suggested retry delay in seconds",
                                    "schema": {"type": "string", "const": "1"},
                                }
                            },
                        ),
                        "409": _error_response(
                            "Idempotency key was reused with a different request body"
                        ),
                        "413": _error_response("Request body is too large"),
                        "415": _error_response(
                            "Content-Type is missing, duplicated, or not "
                            "single-valued application/json"
                        ),
                        "417": _error_response("Expect request headers are unsupported"),
                        "429": _error_response(
                            "Rate limit exceeded",
                            headers={
                                "Retry-After": {
                                    "description": "Suggested retry delay in seconds",
                                    "schema": {"type": "string", "pattern": r"^[1-9]\d*$"},
                                }
                            },
                        ),
                        "500": _error_response("Agent run or trace persistence failed"),
                        "503": _error_response(
                            "Too many concurrent agent runs",
                            headers={
                                "Retry-After": {
                                    "description": "Suggested retry delay in seconds",
                                    "schema": {"type": "string", "const": "1"},
                                }
                            },
                        ),
                        "504": _error_response("Agent run timed out"),
                    },
                }
            },
            "/runtime/run": {
                "post": {
                    "summary": "Run one Codex-style runtime goal",
                    "description": (
                        "Execute the LLM-planned runtime path. A request may include "
                        "a strict plan object for deterministic tests; otherwise the "
                        "runtime uses configured OpenAI-compatible provider settings."
                    ),
                    "operationId": "postRuntimeRun",
                    "security": [{"BearerAuth": []}],
                    "parameters": [_idempotency_key_parameter()],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RuntimeRunRequest"
                                }
                            }
                        },
                    },
                    "responses": {
                        "200": _json_response(
                            "Runtime run completed, failed, or requires approval",
                            "RuntimeRunResponse",
                            headers={
                                "X-Trace-Path": {
                                    "description": (
                                        "Persisted runtime trace artifact path when trace "
                                        "persistence is enabled"
                                    ),
                                    "schema": {"type": "string"},
                                }
                            },
                        ),
                        "400": _error_response("Malformed runtime request or provider config"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "409": _error_response(
                            "Idempotency key was reused with a different request body"
                        ),
                        "413": _error_response("Request body is too large"),
                        "415": _error_response(
                            "Content-Type is missing, duplicated, or not "
                            "single-valued application/json"
                        ),
                        "429": _error_response(
                            "Rate limit exceeded",
                            headers={
                                "Retry-After": {
                                    "description": "Suggested retry delay in seconds",
                                    "schema": {"type": "string", "pattern": r"^[1-9]\d*$"},
                                }
                            },
                        ),
                        "503": _error_response("Run concurrency limit is full"),
                        "504": _error_response("Agent run timed out"),
                    },
                }
            },
            "/runtime/resume": {
                "post": {
                    "summary": "Resume one Codex-style runtime run after approval",
                    "description": (
                        "Load a persisted runtime trace by run_id and continue a "
                        "policy-blocked action using explicit approved_action_ids."
                    ),
                    "operationId": "postRuntimeResume",
                    "security": [{"BearerAuth": []}],
                    "parameters": [_idempotency_key_parameter()],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RuntimeResumeRequest"
                                }
                            }
                        },
                    },
                    "responses": {
                        "200": _json_response(
                            "Runtime run resumed after approval",
                            "RuntimeRunResponse",
                            headers={
                                "X-Trace-Path": {
                                    "description": (
                                        "Persisted resumed runtime trace artifact path"
                                    ),
                                    "schema": {"type": "string"},
                                }
                            },
                        ),
                        "400": _error_response("Malformed resume request or missing trace_dir"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "404": _error_response("Persisted runtime run was not found"),
                        "409": _error_response(
                            "Idempotency key was reused with a different request body"
                        ),
                        "413": _error_response("Request body is too large"),
                        "415": _error_response(
                            "Content-Type is missing, duplicated, or not "
                            "single-valued application/json"
                        ),
                        "429": _error_response(
                            "Rate limit exceeded",
                            headers={
                                "Retry-After": {
                                    "description": "Suggested retry delay in seconds",
                                    "schema": {"type": "string", "pattern": r"^[1-9]\d*$"},
                                }
                            },
                        ),
                        "500": _error_response("Trace read or persistence failed"),
                        "503": _error_response("Run concurrency limit is full"),
                        "504": _error_response("Agent run timed out"),
                    },
                }
            },
            "/runtime/runs/{run_id}": {
                "get": {
                    "summary": "Report one persisted Codex-style runtime run status",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getRuntimeRunStatus",
                    "parameters": [
                        {
                            "name": "run_id",
                            "in": "path",
                            "required": True,
                            "description": "Persisted runtime run identifier",
                            "schema": {"type": "string"},
                        }
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime run status",
                            "RuntimeRunStatusResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "404": _error_response("Persisted runtime run was not found"),
                        "500": _error_response("Runtime trace could not be read"),
                    },
                }
            },
            "/runtime/runs/{run_id}/cancel": {
                "post": {
                    "summary": "Cancel one pending Codex-style runtime run",
                    "description": (
                        "Load a persisted non-terminal runtime trace by run_id and "
                        "mark it cancelled. The owning auth subject may cancel its "
                        "own run; the primary token may cancel any subject run."
                    ),
                    "operationId": "postRuntimeCancel",
                    "security": [{"BearerAuth": []}],
                    "parameters": [
                        {
                            "name": "run_id",
                            "in": "path",
                            "required": True,
                            "description": "Persisted runtime run identifier",
                            "schema": {"type": "string"},
                        },
                        _idempotency_key_parameter(),
                    ],
                    "requestBody": {
                        "required": True,
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RuntimeCancelRequest"
                                }
                            }
                        },
                    },
                    "responses": {
                        "200": _json_response(
                            "Runtime run was cancelled",
                            "RuntimeRunStatusResponse",
                        ),
                        "400": _error_response("Malformed cancel request or missing trace_dir"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "404": _error_response("Persisted runtime run was not found"),
                        "409": _error_response("Runtime run is already terminal"),
                        "413": _error_response("Request body is too large"),
                        "415": _error_response(
                            "Content-Type is missing, duplicated, or not "
                            "single-valued application/json"
                        ),
                        "429": _error_response(
                            "Rate limit exceeded",
                            headers={
                                "Retry-After": {
                                    "description": "Suggested retry delay in seconds",
                                    "schema": {"type": "string", "pattern": r"^[1-9]\d*$"},
                                }
                            },
                        ),
                        "500": _error_response("Trace read or persistence failed"),
                        "503": _error_response("Run concurrency limit is full"),
                    },
                }
            },
            "/runtime/runs/{run_id}/artifacts/{artifact_id}": {
                "get": {
                    "summary": "Return one artifact from a persisted Codex-style runtime run",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getRuntimeArtifact",
                    "parameters": [
                        {
                            "name": "run_id",
                            "in": "path",
                            "required": True,
                            "description": "Persisted runtime run identifier",
                            "schema": {"type": "string"},
                        },
                        {
                            "name": "artifact_id",
                            "in": "path",
                            "required": True,
                            "description": "Artifact identifier from compact runtime status",
                            "schema": {"type": "string"},
                        },
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime artifact",
                            "RuntimeArtifactResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "404": _error_response(
                            "Persisted runtime run or artifact was not found"
                        ),
                        "500": _error_response("Runtime trace could not be read"),
                    },
                }
            },
            "/runtime/runs/{run_id}/artifacts": {
                "get": {
                    "summary": (
                        "List artifact metadata for one persisted Codex-style runtime run"
                    ),
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "listRuntimeArtifacts",
                    "parameters": [
                        {
                            "name": "run_id",
                            "in": "path",
                            "required": True,
                            "description": "Persisted runtime run identifier",
                            "schema": {"type": "string"},
                        }
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime artifact metadata list",
                            "RuntimeArtifactListResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "404": _error_response("Persisted runtime run was not found"),
                        "500": _error_response("Runtime trace could not be read"),
                    },
                }
            },
            "/runtime/runs/{run_id}/timeline": {
                "get": {
                    "summary": "Return a compact timeline for one persisted runtime run",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "getRuntimeTimeline",
                    "parameters": [
                        {
                            "name": "run_id",
                            "in": "path",
                            "required": True,
                            "description": "Persisted runtime run identifier",
                            "schema": {"type": "string"},
                        }
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime compact timeline",
                            "RuntimeTimelineResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                        "404": _error_response("Persisted runtime run was not found"),
                        "500": _error_response("Runtime trace could not be read"),
                    },
                }
            },
            "/runtime/approvals": {
                "get": {
                    "summary": "List pending Codex-style runtime approvals",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "listRuntimeApprovals",
                    "parameters": [
                        {
                            "name": "limit",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Maximum pending approval records to return, "
                                "from 1 to 100"
                            ),
                            "schema": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 100,
                                "default": 50,
                            },
                        },
                        {
                            "name": "auth_subject",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter pending approvals by authenticated "
                                "internal subject"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "tool",
                            "in": "query",
                            "required": False,
                            "description": "Filter pending approvals by tool name",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "min_pending_age_seconds",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter pending approvals older than this many seconds"
                            ),
                            "schema": {"type": "integer", "minimum": 0},
                        },
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime pending approval queue",
                            "RuntimeApprovalQueueResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                    },
                }
            },
            "/runtime/approvals/summary": {
                "get": {
                    "summary": "Summarize pending Codex-style runtime approvals",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "summarizeRuntimeApprovals",
                    "parameters": [
                        {
                            "name": "auth_subject",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter pending approval aggregate by "
                                "authenticated internal subject"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "tool",
                            "in": "query",
                            "required": False,
                            "description": "Filter pending approval aggregate by tool name",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "min_pending_age_seconds",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter pending approvals older than this many seconds"
                            ),
                            "schema": {"type": "integer", "minimum": 0},
                        },
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime pending approval aggregate",
                            "RuntimeApprovalSummaryResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                    },
                }
            },
            "/runtime/runs": {
                "get": {
                    "summary": "List persisted Codex-style runtime run statuses",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "listRuntimeRuns",
                    "parameters": [
                        {
                            "name": "limit",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Maximum persisted runtime runs to return, from 1 to 100"
                            ),
                            "schema": {
                                "type": "integer",
                                "minimum": 1,
                                "maximum": 100,
                                "default": 50,
                            },
                        },
                        {
                            "name": "cursor",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Opaque pagination cursor from a previous runtime "
                                "run list response"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "auth_subject",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by authenticated "
                                "internal subject"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "status",
                            "in": "query",
                            "required": False,
                            "description": "Filter persisted runtime runs by terminal status",
                            "schema": {
                                "type": "string",
                                "enum": [
                                    "cancelled",
                                    "done",
                                    "failed",
                                    "requires_approval",
                                ],
                            },
                        },
                        {
                            "name": "tool",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "tool_names include this tool"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "error_code",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "error_code_counts include this error code"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "latest_failed_error_code",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "latest_failed_error_code matches this error code"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "latest_failed_action_id",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "latest_failed_action_id matches this action id"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "latest_failed_tool",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "latest_failed_tool matches this tool"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "iteration_budget_remaining",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "iteration_budget_remaining equals this count"
                            ),
                            "schema": {"type": "integer", "minimum": 0},
                        },
                        {
                            "name": "artifact_kind",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "artifact_kinds include this artifact kind"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "artifact_format",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "artifact_formats include this artifact format"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "artifact_tag",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "artifact_tags include this artifact tag"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "tag",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact tags "
                                "include this tag"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "metadata_key",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "metadata contains this key"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "metadata_value",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "metadata contains this value"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "has_artifacts",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by whether "
                                "artifacts were produced"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "has_errors",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by whether compact "
                                "summaries contain observation or run-level errors"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "has_failures",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by whether compact "
                                "summaries contain failed observations"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "has_approvals",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by whether compact "
                                "summaries contain approved actions"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "has_pending_approval",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by whether compact "
                                "summaries contain a pending approval action"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "has_final_answer_guardrail",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by whether compact "
                                "summaries contain an applied final-answer guardrail"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "final_answer_guardrail_reason",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose applied "
                                "final-answer guardrail has this reason"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "approved_action_id",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "approved_action_ids include this action id"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "resumed_from_run_id",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs resumed from this "
                                "original run id"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "resumed_by_auth_subject",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs by the subject "
                                "that performed resume"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "pending_approval_tool",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "pending_approval_tool matches this tool"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "pending_approval_action_id",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter persisted runtime runs whose compact "
                                "pending_approval_action_id matches this action id"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime run status list",
                            "RuntimeRunListResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                    },
                }
            },
            "/runtime/runs/summary": {
                "get": {
                    "summary": "Summarize persisted Codex-style runtime runs",
                    "description": _diagnostic_description(),
                    "security": _diagnostic_security(),
                    "operationId": "summarizeRuntimeRuns",
                    "parameters": [
                        {
                            "name": "auth_subject",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter summary to persisted runtime runs by "
                                "authenticated internal subject"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "status",
                            "in": "query",
                            "required": False,
                            "description": "Filter summary by terminal status",
                            "schema": {
                                "type": "string",
                                "enum": [
                                    "cancelled",
                                    "done",
                                    "failed",
                                    "requires_approval",
                                ],
                            },
                        },
                        {
                            "name": "tool",
                            "in": "query",
                            "required": False,
                            "description": "Filter summary by compact tool_names",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "error_code",
                            "in": "query",
                            "required": False,
                            "description": "Filter summary by compact error_code_counts",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "tag",
                            "in": "query",
                            "required": False,
                            "description": "Filter summary by compact run tags",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "metadata_key",
                            "in": "query",
                            "required": False,
                            "description": "Filter summary by compact metadata key",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "metadata_value",
                            "in": "query",
                            "required": False,
                            "description": "Filter summary by compact metadata value",
                            "schema": {"type": "string", "minLength": 1},
                        },
                        {
                            "name": "has_pending_approval",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter summary by whether compact summaries contain "
                                "a pending approval action"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "has_final_answer_guardrail",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter summary by whether compact summaries contain "
                                "an applied final-answer guardrail"
                            ),
                            "schema": {"type": "boolean"},
                        },
                        {
                            "name": "final_answer_guardrail_reason",
                            "in": "query",
                            "required": False,
                            "description": (
                                "Filter summary by applied final-answer guardrail "
                                "reason"
                            ),
                            "schema": {"type": "string", "minLength": 1},
                        },
                    ],
                    "responses": {
                        "200": _json_response(
                            "Runtime run fleet summary",
                            "RuntimeRunSummaryResponse",
                        ),
                        "400": _error_response("Runtime trace persistence is not configured"),
                        "401": _error_response("Missing or invalid bearer token"),
                    },
                }
            },
        },
}


def _trace_permission_policy_properties() -> Dict[str, Dict[str, str]]:
    return {
        "trace_directory_permissions": {"type": "string", "const": "0700"},
        "trace_file_permissions": {"type": "string", "const": "0600"},
        "trace_probe_file_permissions": {"type": "string", "const": "0600"},
    }


def _llm_provider_audit_properties() -> Dict[str, Dict[str, Any]]:
    return {
        "llm_provider": {
            "type": "string",
            "enum": ["openai_compatible", "unconfigured"],
        },
        "llm_base_url": {"type": "string"},
        "llm_model": {"type": "string"},
        "llm_api_key_configured": {
            "type": "string",
            "enum": ["true", "false"],
        },
        "llm_timeout_seconds": {"type": "string"},
        "llm_max_retries": {"type": "string"},
        "llm_retry_backoff_seconds": {"type": "string"},
    }


def _diagnostic_audit_properties() -> Dict[str, Dict[str, Any]]:
    properties: Dict[str, Dict[str, Any]] = {
        "auth_subject_count": {"type": "string"},
        "idempotency_cache_backend": {"type": "string", "enum": ["memory", "sqlite"]},
        "idempotency_cache_path_configured": {"type": "string", "enum": ["true", "false"]},
        "runtime_allowed_tools": {"type": "string"},
        "runtime_allowed_tools_by_subject_count": {"type": "string"},
        "runtime_pending_approval_stale_seconds": {"type": "string"},
    }
    properties.update(_trace_permission_policy_properties())
    properties.update(_llm_provider_audit_properties())
    return properties


def _json_response(
    description: str,
    schema_name: str,
    *,
    headers: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    response = {
        "description": description,
        "content": {
            "application/json": {
                "schema": {"$ref": f"#/components/schemas/{schema_name}"},
            }
        },
    }
    response["headers"] = _response_headers(headers)
    return response


def _object_response(description: str) -> Dict[str, Any]:
    return {
        "description": description,
        "headers": _response_headers(),
        "content": {
            "application/json": {
                "schema": {"type": "object"},
            }
        },
    }


def _text_response(description: str) -> Dict[str, Any]:
    return {
        "description": description,
        "headers": _response_headers(),
        "content": {
            "text/plain": {
                "schema": {"type": "string"},
            }
        },
    }


def _empty_response(description: str) -> Dict[str, Any]:
    return {
        "description": description,
        "headers": _response_headers(),
    }


def _runtime_run_status_properties(*, include_pending_approval: bool) -> Dict[str, Any]:
    properties = {
        "trace_type": {
            "type": "string",
            "const": RUNTIME_TRACE_TYPE,
        },
        "run_id": {"type": "string"},
        "status": {
            "type": "string",
            "enum": ["cancelled", "done", "failed", "requires_approval"],
        },
        "goal": {"type": "string"},
        "auth_subject": {"type": "string"},
        "resumed_by_auth_subject": {"type": "string"},
        "metadata": {
            "type": "object",
            "additionalProperties": {"type": "string"},
        },
        "metadata_keys": {
            "type": "array",
            "items": {"type": "string"},
        },
        "tags": {
            "type": "array",
            "items": {"type": "string"},
        },
        "answer": {"type": "string"},
        "final_answer_guardrail": _final_answer_guardrail_schema(),
        "trace_path": {"type": "string"},
        "iteration_count": {"type": "string"},
        "max_iterations": {"type": "string"},
        "iteration_budget_remaining": {"type": "string"},
        "plan_count": {"type": "string"},
        "observation_count": {"type": "string"},
        "event_count": {"type": "string"},
        "progress_event_count": {"type": "string"},
        "failed_observation_count": {"type": "string"},
        "planner_failure_count": {"type": "string"},
        "tool_failure_count": {"type": "string"},
        "approval_required_count": {"type": "string"},
        "latest_failed_action_id": {"type": "string"},
        "latest_failed_tool": {"type": "string"},
        "latest_failed_error_code": {"type": "string"},
        "approved_action_count": {"type": "string"},
        "approved_action_ids": {
            "type": "array",
            "items": {"type": "string"},
        },
        "error_code_counts": {
            "type": "object",
            "additionalProperties": {"type": "string"},
        },
        "latest_plan_action_count": {"type": "string"},
        "latest_plan_action_ids": {
            "type": "array",
            "items": {"type": "string"},
        },
        "dependency_edge_count": {"type": "string"},
        "tool_names": {
            "type": "array",
            "items": {"type": "string"},
        },
        "artifact_count": {"type": "string"},
        "artifact_ids": {
            "type": "array",
            "items": {"type": "string"},
        },
        "artifact_kinds": {
            "type": "array",
            "items": {"type": "string"},
        },
        "artifact_formats": {
            "type": "array",
            "items": {"type": "string"},
        },
        "artifact_tags": {
            "type": "array",
            "items": {"type": "string"},
        },
        "artifact_total_bytes": {"type": "string"},
        "artifact_bytes_by_kind": {
            "type": "object",
            "additionalProperties": {"type": "string"},
        },
        "pending_approval_action_id": {"type": "string"},
        "pending_approval_tool": {"type": "string"},
        "resumed_from_run_id": {"type": "string"},
        "cancelled_at": {"type": "string"},
        "cancelled_by_auth_subject": {"type": "string"},
        "cancel_reason": {"type": "string"},
        "started_at": {"type": "string"},
        "completed_at": {"type": "string"},
        "duration_seconds": {
            "type": "string",
            "pattern": r"^\d+\.\d{4}$",
        },
        "error_code": {"type": "string"},
        "error": {"type": "string"},
    }
    if include_pending_approval:
        properties["pending_approval"] = {"type": "object"}
    return properties


def _final_answer_guardrail_schema() -> Dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "applied": {"type": "string", "enum": ["true"]},
            "reason": {
                "type": "string",
                "enum": [
                    "runtime_identity_boundary",
                    "runtime_deployment_boundary",
                ],
            },
            "original_answer_omitted": {"type": "string", "enum": ["true"]},
        },
        "additionalProperties": False,
    }


def _error_response(
    description: str,
    *,
    headers: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    return {
        "description": description,
        "headers": _response_headers(headers),
        "content": {
            "application/json": {
                "schema": {"$ref": "#/components/schemas/ErrorResponse"},
            }
        },
    }


def _response_headers(headers: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    merged = dict(COMMON_RESPONSE_HEADERS)
    if headers:
        merged.update(headers)
    return merged


def _idempotency_key_parameter() -> Dict[str, Any]:
    return {
        "name": "Idempotency-Key",
        "in": "header",
        "required": False,
        "description": (
            "Optional retry key scoped to this execution route and resource when "
            "applicable; must be printable ASCII."
        ),
        "schema": {"type": "string", "maxLength": 128},
    }


def _diagnostic_security() -> list[Dict[str, list[str]]]:
    return [{"BearerAuth": []}, {}]


def _diagnostic_description() -> str:
    return (
        "May require bearer authentication when runtime diagnostic protection "
        "is enabled."
    )
